package com.ssafy.edu.awesomeproject.domain.notification.entity;

public enum NotificationType {
    POST_COMMENT_CREATED,
    POST_REPORTED,
    COMMENT_REPORTED,
    REPORT_PROCESSED_BLINDED,
    REPORT_PROCESSED_REJECTED,
    POST_BLINDED,
    COMMENT_BLINDED,
    MANUAL_SAVINGS_COMPLETED,
    MANUAL_WITHDRAWAL_COMPLETED,
    AUTO_SAVINGS_COMPLETED,
    FINANCE_GENERIC,
    CONSUMPTION_REPORT_READY
}
